version: "3"
services:
  course-service:
    build: ./first-demo
    volumes:
      - ./first-demo:/usr/src/app
    ports:
      - 5001:8080
  website:
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 5002:80
    depends_on:
      - course-service
